### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by JTrotta** [ppatierno/gnatmq#11]
Hello,
what are the QNATMQ performances? I mean number of concurrent connections, latency, etc.

Thank you

**Comment by ppatierno** [comment]
Sorry but I have never executed a benchmark on the broker.

**Comment by AngeloBestetti** [comment]
Look´s like he does not want to go forward with this project. Moving to IBM Message Sight!

**Comment by ppatierno** [comment]
It's not absolutely true ! The GnatMQ is an open source project developed and supported in my free/spare time. It's mean that I can follow the project itself in that time and not as my daily job.
Last weeks I merged some pull requests ... it's great to see project's friends to improve it. It's a community project.
Of course the IBM Message Sight is a professional project full supported by IBM as a daily job for a lot of engineers. It's quite different.
However, my GnatMQ is still alive and I'll support it as well as possible.

**Comment by AngeloBestetti** [comment]
Your project it´s very nice, but still missing a lot of features. I suggest you open a Donation Program so we can put you to work LOL!

**Comment by ppatierno** [comment]
I don't work in the open source for donation, just for passion. I agree with yon on missing features. Thanks to its open source nature, developers can add above features if they need.
I'll try to support it in the best way but the free/spare time is always too much few :-)

**Comment by JTrotta** [comment]
Hello Paolo,
your project is simply great, and I really like to contribute. I would like to implement the persistence using Litesql. Tell me the best way to help you.

**Comment by dkkriste** [comment]
btw, I will in all likelyhood do some performance testing of the broker in january

**Comment by JTrotta** [comment]
To test performance I suggest using TT3 (search on github). I ask to Paolo, what is the right way to perform the test.

Thank you

**Comment by dkkriste** [comment]
was planning on running a broker on a vm in azure, and then spinning up clients on other VMs until things stop working
